if __name__ == "__main__":
    print("=== CYBER ARCHIVES - PRESERVATION SYSTEM ===\n")
    print("Initializing new storage unit: new_discovery.txt")
    f = open("new_discovery.txt", "w")
    f.write("[ENTRY 001] New quantum algorithm discovered\n")
    f.write("[ENTRY 002] Efficiency increased by 347%\n")
    f.write("[ENTRY 003] Archived by Data Archivist trainee\n")
    f.close()
    f1 = open("new_discovery.txt", "r")
    content = f1.read()
    f1.close()

    print("Storage unit created successfully...")
    print("\nInscribing preservation data...")
    print(content)
    print("Data inscription complete. Storage unit sealed.")
    print("Archive 'new_discovery.txt' ready for long-term preservation.")
